Debug=true

[Web]
## 生产者的topic 随用随定
## 消费者需要提前 定好消费


[Control]
Switch=true
[Control.SuffixUidNotReport]
1=true

## chan 队列
[ChanQueue]
	EsAddr = ["http://elastic:9200"]
	EsIndex  =   "user-event"

[Nsq]
Topics= ["user_event"]
ConsumerIds = ["user_event_customer"]
LookUpdAddress= ["nsqlookupd0:4161","nsqlookupd0:4161","nsqlookupd0:4161"]

[signAuth]
## 是否验证
Enable = true
Expire = "10m"
Sep = "#"

###  前缀忽略规则
IgnorePrefixList = []
#### app
[signAuth.App]
    "jiaoyishi_soft" = "123456"
    "zlj_software" = "jJPqrDs9"
